// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For PgBouncer setups:
    // - DIRECT_URL should bypass PgBouncer (used by migrations/introspection)
    // - DATABASE_URL can be the pooled PgBouncer URL (used by the app)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
